=== JVancata/4iz238/kiosek.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    attributeFormDefault="qualified" targetNamespace="urn:vse.cz:vanj23:kiosek"
    xmlns="urn:vse.cz:vanj23:kiosek" xmlns:kiosek="urn:vse.cz:vanj23:kiosek">

    <xs:element name="kiosek" type="kiosekType">
        <!-- Kategorie jídel musí být unikátní -->
        <xs:key name="kategorie_jidel_key">
            <xs:selector xpath="./kiosek:kategorieJidel/kiosek:kategorie"/>
            <xs:field xpath="."/>
        </xs:key>
        <!-- Názvy jídel musí být unikátní -->
        <xs:key name="polozky_key">
            <xs:selector xpath="./kiosek:polozky/kiosek:polozka"/>
            <xs:field xpath="kiosek:nazev"/>
        </xs:key>
        <!-- Položka může obsahovat pouze předepsanou kategorii jídel -->
        <xs:keyref refer="kategorie_jidel_key" name="pouze_validni_kategorie_key">
            <xs:selector xpath="./kiosek:polozky/kiosek:polozka"/>
            <xs:field xpath="kiosek:kategorie"/>
        </xs:keyref>
        <!-- Existující úprava jídla musí být unikátní -->
        <xs:key name="existujici_upravy_key">
            <xs:selector xpath="./kiosek:existujiciUpravy/kiosek:uprava"/>
            <xs:field xpath="kiosek:nazev"/>
        </xs:key>
        <!-- Jídlo může nabízet pouze existující úpravy jídel -->
        <xs:keyref refer="existujici_upravy_key" name="pouze_existujici_upravy_key">
            <xs:selector xpath="./kiosek:polozky/kiosek:polozka/kiosek:povoleneUpravy/kiosek:uprava"/>
            <xs:field xpath="."/>
        </xs:keyref>
        <!-- Kupony musí mít unikátní název -->
        <xs:key name="kupony_key">
            <xs:selector xpath="./kiosek:kupony/kiosek:kupon"/>
            <xs:field xpath="kiosek:nazev"/>
        </xs:key>
        <!-- Kupon může obsahovat pouze existující názvy jídel -->
        <xs:keyref refer="polozky_key" name="pouze_existujici_jidla_v_kuponu_key">
            <xs:selector xpath="./kiosek:kupony/kiosek:kupon/kiosek:obsah/kiosek:polozka"/>
            <xs:field xpath="."/>
        </xs:keyref>
        <!-- Položka účtenky s typem kupon může obsahovat pouze validní názvy kuponů -->
        <!-- PŘES SCHEMA NEJDE, UDELAME TO SCHEMATRONEM -->
        <!--<xs:keyref refer="kupony_key" name="pouze_kupon_key">
            <xs:selector xpath="./kiosek:uctenky/kiosek:uctenka/kiosek:polozkyUctenky/kiosek:polozkaUctenky[@kiosek:typ='Kupon']"/>
            <xs:field xpath=""/>
        </xs:keyref>
        -->
        <!-- Další schmatron check - cena se rovná součtu položek v objednávce -->
    </xs:element>

    <xs:complexType name="kiosekType">
        <xs:sequence>
            <xs:element name="kategorieJidel" type="kategorieJidelType"> </xs:element>
            <xs:element name="existujiciUpravy" type="existujiciUpravyType"/>
            <xs:element name="polozky" type="polozkyType"/>
            
            <xs:element name="kupony" type="kuponyType"/>
            <xs:element name="uctenky" type="uctenkyType"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Účtenky -->
    <xs:complexType name="uctenkyType">
        <xs:sequence>
            <xs:element name="uctenka" type="uctenkaType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="uctenkaType">
        <xs:sequence>
            <xs:element name="id" type="idType"/>
            <xs:element name="vystaveno" type="xs:dateTime"/>
            <xs:element name="celkem" type="vetsiNezNula"/>
            <xs:element name="polozkyUctenky" type="polozkyUctenkyType"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Položky účtenky -->
    <xs:complexType name="polozkyUctenkyType">
        <xs:sequence>
            <xs:element name="polozkaUctenky" type="polozkaUctenkyType" minOccurs="1"
                maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="polozkaUctenkyType">
        <xs:sequence>
            <xs:element name="nazev" type="neprazdnyRetezec">
                <!-- KEYREF!!! -->
            </xs:element>
            <xs:element name="cena" type="vetsiNezNula"/>
            <xs:element name="pocet" type="vetsiNezNula"/>
            <xs:element name="upravaPolozky" type="upravaNaUctenceType" minOccurs="0" maxOccurs="unbounded">
                <!-- KEYREF -->
            </xs:element>
        </xs:sequence>
        <xs:attribute name="typ" type="typPolozkyVUctence" use="required"/>
    </xs:complexType>

    <xs:complexType name="upravaNaUctenceType">
        <xs:sequence>
            <xs:element name="upravovanaPolozka" type="neprazdnyRetezec"/>
            <xs:element name="uprava" type="neprazdnyRetezec" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="typPolozkyVUctence">
        <xs:restriction base="neprazdnyRetezec">
            <xs:enumeration value="Samostatná"/>
            <xs:enumeration value="Kupon"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Kupony -->

    <xs:complexType name="kuponyType">
        <xs:sequence>
            <xs:element name="kupon" minOccurs="0" maxOccurs="unbounded" type="kuponType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="kuponType">
        <xs:sequence>
            <xs:element name="nazev" type="neprazdnyRetezec"/>
            <xs:element name="cena" type="vetsiNezNula"/>
            <xs:element name="obsah" type="obsahKuponuType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="obsahKuponuType">
        <xs:sequence>
            <xs:element name="polozka" type="neprazdnyRetezec" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Položka -->
    <xs:complexType name="polozkaType">
        <xs:sequence>
            <xs:element name="nazev" type="neprazdnyRetezec"/>
            <xs:element name="cena" type="vetsiNezNula"/>
            <xs:element name="kategorie" type="neprazdnyRetezec"/>
            <xs:element name="povoleneUpravy" type="povoleneUpravyType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="obrazek" type="obrazekType"/>
        </xs:sequence>
        <xs:attribute name="typ" type="typJidlaType" use="required"/>
    </xs:complexType>

    <xs:complexType name="povoleneUpravyType">
        <xs:sequence>
            <xs:element name="uprava" type="neprazdnyRetezec" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Typy jídla -->
    <xs:simpleType name="typJidlaType">
        <xs:restriction base="neprazdnyRetezec">
            <xs:enumeration value="Hlavní jídlo"/>
            <xs:enumeration value="Nápoj"/>
            <xs:enumeration value="Příloha"/>
            <xs:enumeration value="Finger food"/>
            <xs:enumeration value="Desert"/>
            <xs:enumeration value="Omáčka"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Položky -->
    <xs:complexType name="polozkyType">
        <xs:sequence>
            <xs:element name="polozka" type="polozkaType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Kategorie jídel -->

    <xs:complexType name="kategorieJidelType">
        <xs:sequence>
            <xs:element name="kategorie" type="neprazdnyRetezec" minOccurs="1" maxOccurs="unbounded"
            />
        </xs:sequence>
    </xs:complexType>

    <!-- Úpravy -->

    <xs:complexType name="existujiciUpravyType">
        <xs:sequence>
            <xs:element name="uprava" type="existujiciUpravaType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="existujiciUpravaType">
        <xs:sequence>
            <xs:element name="nazev" type="neprazdnyRetezec"/>
            <xs:element name="typ" type="typUpravyType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="typUpravyType">
        <xs:restriction base="neprazdnyRetezec">
            <xs:enumeration value="Volitelné"/>
            <xs:enumeration value="Extra"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- BASIC TYPY -->
    <xs:simpleType name="idType">
        <xs:restriction base="neprazdnyRetezec">
            <xs:pattern value="\d{3}-[A-Z]{3}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="obrazekType">
        <xs:restriction base="xs:anyURI">
            <!-- Mozna tu dodela regex nejakej? -->
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="vetsiNezNula">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="neprazdnyRetezec">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== JVancata/4iz238/kiosek.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="kiosek.sch" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<kiosek:kiosek xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:vse.cz:vanj23:kiosek kiosek.xsd" xmlns="urn:vse.cz:vanj23:kiosek"
    xmlns:kiosek="urn:vse.cz:vanj23:kiosek">
    <!-- Kategorie jídel pro zobrazení v menu kiosku -->
    <kiosek:kategorieJidel>
        <kiosek:kategorie>Hovězí burgery</kiosek:kategorie>
        <kiosek:kategorie>Wrapy</kiosek:kategorie>
        <kiosek:kategorie>Studené nápoje</kiosek:kategorie>
        <kiosek:kategorie>Horké nápoje</kiosek:kategorie>
        <kiosek:kategorie>Hranolky</kiosek:kategorie>
        <kiosek:kategorie>Salát</kiosek:kategorie>
        <kiosek:kategorie>Desert</kiosek:kategorie>
        <kiosek:kategorie>Finger food</kiosek:kategorie>
        <kiosek:kategorie>Omáčka</kiosek:kategorie>
    </kiosek:kategorieJidel>
    <!-- Seznam všech možných úprav, které lze u jídel provést -->
    <kiosek:existujiciUpravy>
        <!-- Hlavní jídla -->
        <kiosek:uprava>
            <kiosek:nazev>Cibule čerstvá</kiosek:nazev>
            <kiosek:typ>Volitelné</kiosek:typ>
        </kiosek:uprava>
        <kiosek:uprava>
            <kiosek:nazev>Plátek masa navíc</kiosek:nazev>
            <kiosek:typ>Extra</kiosek:typ>
        </kiosek:uprava>
        <kiosek:uprava>
            <kiosek:nazev>Plátek slaniny navíc</kiosek:nazev>
            <kiosek:typ>Extra</kiosek:typ>
        </kiosek:uprava>
        <kiosek:uprava>
            <kiosek:nazev>Bezlepková houska</kiosek:nazev>
            <kiosek:typ>Volitelné</kiosek:typ>
        </kiosek:uprava>
        <kiosek:uprava>
            <kiosek:nazev>Rajče</kiosek:nazev>
            <kiosek:typ>Volitelné</kiosek:typ>
        </kiosek:uprava>
        <!-- Deserty -->
        <kiosek:uprava>
            <kiosek:nazev>Karamelový toping</kiosek:nazev>
            <kiosek:typ>Extra</kiosek:typ>
        </kiosek:uprava>
        <kiosek:uprava>
            <kiosek:nazev>Čokoládový toping</kiosek:nazev>
            <kiosek:typ>Extra</kiosek:typ>
        </kiosek:uprava>
        <kiosek:uprava>
            <kiosek:nazev>Jahodový toping</kiosek:nazev>
            <kiosek:typ>Extra</kiosek:typ>
        </kiosek:uprava>
    </kiosek:existujiciUpravy>
    <!-- Jídla, které jsou v systému evidována a lze z nich skládat nabídka -->
    <kiosek:polozky>
        <kiosek:polozka kiosek:typ="Hlavní jídlo">
            <kiosek:nazev>BigMac</kiosek:nazev>
            <kiosek:cena>99</kiosek:cena>
            <kiosek:kategorie>Hovězí burgery</kiosek:kategorie>
            <kiosek:povoleneUpravy>
                <kiosek:uprava>Cibule čerstvá</kiosek:uprava>
                <kiosek:uprava>Plátek slaniny navíc</kiosek:uprava>
                <kiosek:uprava>Bezlepková houska</kiosek:uprava>
            </kiosek:povoleneUpravy>
            <kiosek:obrazek>https://jakub.dev/bigmac.png</kiosek:obrazek>
        </kiosek:polozka>
        <kiosek:polozka kiosek:typ="Hlavní jídlo">
            <kiosek:nazev>McRoyal</kiosek:nazev>
            <kiosek:cena>99</kiosek:cena>
            <kiosek:kategorie>Hovězí burgery</kiosek:kategorie>
            <kiosek:obrazek>https://www.mcdonalds.cz/uploads/images/products/7-cz/c9619b204fb3adc0ee229c4e0b603942-medium_2x.webp</kiosek:obrazek>
        </kiosek:polozka>
        <kiosek:polozka kiosek:typ="Hlavní jídlo">
            <kiosek:nazev>McWrap grilled</kiosek:nazev>
            <kiosek:cena>99</kiosek:cena>
            <kiosek:kategorie>Wrapy</kiosek:kategorie>
            <kiosek:povoleneUpravy>
                <kiosek:uprava>Rajče</kiosek:uprava>
            </kiosek:povoleneUpravy>
            <kiosek:obrazek>https://www.mcdonalds.cz/uploads/images/products/12-cz/534a9f8c549f37090520589dd95f1f13-medium_2x.webp</kiosek:obrazek>
        </kiosek:polozka>
        <kiosek:polozka kiosek:typ="Hlavní jídlo">
            <kiosek:nazev>McWrap crispy</kiosek:nazev>
            <kiosek:cena>99</kiosek:cena>
            <kiosek:kategorie>Wrapy</kiosek:kategorie>
            <kiosek:obrazek>https://www.mcdonalds.cz/assets/web/img/share.jpg</kiosek:obrazek>
        </kiosek:polozka>
        <kiosek:polozka kiosek:typ="Nápoj">
            <kiosek:nazev>Coca Cola 0.5 l</kiosek:nazev>
            <kiosek:cena>39</kiosek:cena>
            <kiosek:kategorie>Studené nápoje</kiosek:kategorie>
            <kiosek:obrazek>https://www.mcdonalds.cz/assets/web/img/share.jpg</kiosek:obrazek>
        </kiosek:polozka>
        <kiosek:polozka kiosek:typ="Nápoj">
            <kiosek:nazev>Čaj Lipton 0.3 l - zelený </kiosek:nazev>
            <kiosek:cena>39</kiosek:cena>
            <kiosek:kategorie>Horké nápoje</kiosek:kategorie>
            <kiosek:obrazek>https://www.mcdonalds.cz/assets/web/img/share.jpg</kiosek:obrazek>
        </kiosek:polozka>
        <kiosek:polozka kiosek:typ="Příloha">
            <kiosek:nazev>Velké hranolky</kiosek:nazev>
            <kiosek:cena>49</kiosek:cena>
            <kiosek:kategorie>Hranolky</kiosek:kategorie>
            <kiosek:obrazek>https://www.mcdonalds.cz/assets/web/img/share.jpg</kiosek:obrazek>
        </kiosek:polozka>
        <kiosek:polozka kiosek:typ="Příloha">
            <kiosek:nazev>Zahradní salát</kiosek:nazev>
            <kiosek:cena>49</kiosek:cena>
            <kiosek:kategorie>Salát</kiosek:kategorie>
            <kiosek:obrazek>https://www.mcdonalds.cz/assets/web/img/share.jpg</kiosek:obrazek>
        </kiosek:polozka>
        <kiosek:polozka kiosek:typ="Finger food">
            <kiosek:nazev>Smažené hermelíny - 3 Ks</kiosek:nazev>
            <kiosek:cena>49</kiosek:cena>
            <kiosek:kategorie>Finger food</kiosek:kategorie>
            <kiosek:obrazek>https://www.mcdonalds.cz/assets/web/img/share.jpg</kiosek:obrazek>
        </kiosek:polozka>
        <kiosek:polozka kiosek:typ="Desert">
            <kiosek:nazev>Sezónní taštička</kiosek:nazev>
            <kiosek:cena>49</kiosek:cena>
            <kiosek:kategorie>Desert</kiosek:kategorie>
            <kiosek:obrazek>https://www.mcdonalds.cz/assets/web/img/share.jpg</kiosek:obrazek>
        </kiosek:polozka>
        <kiosek:polozka kiosek:typ="Desert">
            <kiosek:nazev>McSundae - zmrzlina</kiosek:nazev>
            <kiosek:cena>39</kiosek:cena>
            <kiosek:kategorie>Desert</kiosek:kategorie>
            <kiosek:povoleneUpravy>
                <kiosek:uprava>Karamelový toping</kiosek:uprava>
                <kiosek:uprava>Čokoládový toping</kiosek:uprava>
                <kiosek:uprava>Jahodový toping</kiosek:uprava>
            </kiosek:povoleneUpravy>
            <kiosek:obrazek>https://www.mcdonalds.cz/assets/web/img/share.jpg</kiosek:obrazek>
        </kiosek:polozka>
        <kiosek:polozka kiosek:typ="Omáčka">
            <kiosek:nazev>Sladkokyselá omáčka</kiosek:nazev>
            <kiosek:cena>9</kiosek:cena>
            <kiosek:kategorie>Omáčka</kiosek:kategorie>
            <kiosek:obrazek>https://www.mcdonalds.cz/assets/web/img/share.jpg</kiosek:obrazek>
        </kiosek:polozka>
        <kiosek:polozka kiosek:typ="Omáčka">
            <kiosek:nazev>Kari omáčka</kiosek:nazev>
            <kiosek:cena>9</kiosek:cena>
            <kiosek:kategorie>Omáčka</kiosek:kategorie>
            <kiosek:obrazek>https://www.mcdonalds.cz/assets/web/img/share.jpg</kiosek:obrazek>
        </kiosek:polozka>
        <kiosek:polozka kiosek:typ="Omáčka">
            <kiosek:nazev>Kečup</kiosek:nazev>
            <kiosek:cena>9</kiosek:cena>
            <kiosek:kategorie>Omáčka</kiosek:kategorie>
            <kiosek:obrazek>https://www.mcdonalds.cz/assets/web/img/share.jpg</kiosek:obrazek>
        </kiosek:polozka>
    </kiosek:polozky>
    <!-- Vyhodne nabidky z aplikace ktere obsahuji kombinaci nekolika polozek z nabidky nebo slevu na jeden produkt -->
    <kiosek:kupony>
        <kiosek:kupon>
            <kiosek:nazev>BigMac menu s velkými hranolkami a Coca Colou</kiosek:nazev>
            <kiosek:cena>125</kiosek:cena>
            <kiosek:obsah>
                <kiosek:polozka>BigMac</kiosek:polozka>
                <kiosek:polozka>Velké hranolky</kiosek:polozka>
                <kiosek:polozka>Coca Cola 0.5 l</kiosek:polozka>
            </kiosek:obsah>
        </kiosek:kupon>
        <kiosek:kupon>
            <kiosek:nazev>McSundae v super slevě!</kiosek:nazev>
            <kiosek:cena>30</kiosek:cena>
            <kiosek:obsah>
                <kiosek:polozka>McSundae - zmrzlina</kiosek:polozka>
            </kiosek:obsah>
        </kiosek:kupon>
    </kiosek:kupony>
    <kiosek:uctenky>
        <kiosek:uctenka>
            <!-- Náhodné ID účtenky -->
            <kiosek:id>232-ASC</kiosek:id>
            <kiosek:vystaveno>2022-12-05T09:05:00</kiosek:vystaveno>
            <kiosek:celkem>223</kiosek:celkem>
            <kiosek:polozkyUctenky>
                <!-- Samostatná položka z nabídky -->
                <kiosek:polozkaUctenky kiosek:typ="Samostatná">
                    <kiosek:nazev>Sezónní taštička</kiosek:nazev>
                    <kiosek:cena>49</kiosek:cena>
                    <kiosek:pocet>2</kiosek:pocet>
                </kiosek:polozkaUctenky>
                <!-- Obsahuje předem definované položky -->
                <kiosek:polozkaUctenky kiosek:typ="Kupon">
                    <kiosek:nazev>BigMac menu s velkými hranolkami a Coca Colou</kiosek:nazev>
                    <kiosek:cena>125</kiosek:cena>
                    <kiosek:pocet>1</kiosek:pocet>
                </kiosek:polozkaUctenky>
            </kiosek:polozkyUctenky>
        </kiosek:uctenka>
        <kiosek:uctenka>
            <kiosek:id>843-PPG</kiosek:id>
            <kiosek:vystaveno>2022-12-06T11:05:00</kiosek:vystaveno>
            <kiosek:celkem>30</kiosek:celkem>
            <kiosek:polozkyUctenky>
                <kiosek:polozkaUctenky kiosek:typ="Kupon">
                    <kiosek:nazev>McSundae v super slevě!</kiosek:nazev>
